### ISSUE TITLE
Not all ranked members are able to see star backups

### ISSUE THREAD

**Issue by 10kLakes** [luisr96/discord-bot-starhunters#10]
I've been told that the backups list isn't fully visible to all ranked members as intended. Specifically, if I `/hold` a star, another ranked member may not be able to see that star on backups. 

I believe you're using the discord role "Ranked" to determine who should be permitted to see all the backups. I just ensured that everyone is properly marked as Ranked (and they were).

Two people who have reported this problem on Discord are Shop N Drop:

> Not sure if it's been suggested but have it so 2nd rank+ can see the world the backups are on? So we can verify if a backup star gets released in star miners/keep track of it.

and xpajtimi:

> this says we can see, but is not working as intended, we can't see other's backup worlds

**Comment by luisr96** [comment]
thank you, will look into it
